import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { getSession } from "@/utils/getSession";
import { Providers } from "@/providers";
import type { Metadata } from "next";
import "@/lib/zod/config";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers session={session}>
          {children}
          <ToastContainer theme="colored" position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
